#!/usr/bin/env node
var ansi2svg = require('./index')
const fs = require('fs')

const out = process.env.ANSI2SVG_OUTPUT_FILE
  ? fs.createWriteStream(process.env.ANSI2SVG_OUTPUT_FILE)
  : process.stdout
process.stdin.pipe(ansi2svg()).pipe(out)
